BestRestaurants/Models/BestRestaurantsContext.cs
using Microsoft.EntityFrameworkCore;

namespace BestRestaurants.Models
{
  public class BestRestaurantsContext : DbContext
  {
    public DbSet<Restaurant> Restaurants { get; set; }
    public DbSet<Cuisine> Cuisines { get; set; }

    public BestRestaurantsContext(DbContextOptions options) : base(options) { }
  }
}

BestRestaurants/Models/Cuisine.cs
namespace BestRestaurants.Models
{
  public class Cuisine
  {
    public int CuisineId { get; set; }
    public string Description { get; set; }
    public int RestaurantId { get; set; }
    public Restaurant Restaurant { get; set; }
  }
}

BestRestaurants/Models/Restaurant.cs
using System.Collections.Generic;

namespace BestRestaurants.Models
{
  public class Restaurant
  {
    public int RestaurantId { get; set; }
    public string Name { get; set; }
    public List<Cuisine> Cuisines { get; set; }
  }
}

BestRestaurants/Controllers/CuisinesController.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using BestRestaurants.Models;
using System.Collections.Generic;
using System.Linq;

namespace BestRestaurants.Controllers
{
  public class CuisinesController : Controller
  {
    private readonly BestRestaurantsContext _db;

    public CuisinesController(BestRestaurantsContext db)
    {
      _db = db;
    }

    public ActionResult Index()
    {
      List<Cuisine> model = _db.Cuisines
                            .Include(cuisine => cuisine.Restaurant)
                            .ToList();
      return View(model);
    }

    public ActionResult Create()
    {
      ViewBag.RestaurantId = new SelectList(_db.Restaurants, "RestaurantId", "Name");
      return View();
    }

    [HttpPost]
    public ActionResult Create(Cuisine cuisine)
    {
      if (cuisine.RestaurantId == 0)
      {
        return RedirectToAction("Create");
      }
      _db.Cuisines.Add(cuisine);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Details(int id)
    {
      Cuisine thisCuisine = _db.Cuisines
                          .Include(cuisine => cuisine.Restaurant)
                          .FirstOrDefault(cuisine => cuisine.CuisineId == id);
      return View(thisCuisine);
    }

    public ActionResult Edit(int id)
    {
      Cuisine thisCuisine = _db.Cuisines.FirstOrDefault(cuisine => cuisine.CuisineId == id);
      ViewBag.RestaurantId = new SelectList(_db.Restaurants, "RestaurantId", "Name");
      return View(thisCuisine);
    }

    [HttpPost]
    public ActionResult Edit(Cuisine cuisine)
    {
      _db.Cuisines.Update(cuisine);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Delete(int id)
    {
      Cuisine thisCuisine = _db.Cuisines.FirstOrDefault(cuisine => cuisine.CuisineId == id);
      return View(thisCuisine);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      Cuisine thisCuisine = _db.Cuisines.FirstOrDefault(cuisine => cuisine.CuisineId == id);
      _db.Cuisines.Remove(thisCuisine);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
  }
}

BestRestaurants/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace ToDoList.Controllers
{
    public class HomeController : Controller
    {

      [HttpGet("/")]
      public ActionResult Index()
      {
        return View();
      }

    }
}

BestRestaurants/Controllers/RestaurantsController.cs
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using BestRestaurants.Models;
using System.Collections.Generic;
using System.Linq;

namespace BestRestaurants.Controllers
{
  public class RestaurantsController : Controller
  {
    private readonly BestRestaurantsContext _db;

    public RestaurantsController(BestRestaurantsContext db)
    {
      _db = db;
    }

    public ActionResult Index()
    {
      List<Restaurant> model = _db.Restaurants.ToList();
      return View(model);
    }

    public ActionResult Create()
    {
      return View();
    }

    [HttpPost]
    public ActionResult Create(Restaurant restaurant)
    {
      _db.Restaurants.Add(restaurant);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Details(int id)
    {
      Restaurant thisRestaurant = _db.Restaurants
                                  .Include(restaurant => restaurant.Cuisines)
                                  .FirstOrDefault(restaurant => restaurant.RestaurantId == id);
      return View(thisRestaurant);
    }

    public ActionResult Edit(int id)
    {
      Restaurant thisRestaurant = _db.Restaurants.FirstOrDefault(restaurant => restaurant.RestaurantId == id);
      return View(thisRestaurant);
    }

    [HttpPost]
    public ActionResult Edit(Restaurant restaurant)
    {
      _db.Restaurants.Update(restaurant);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Delete(int id)
    {
      Restaurant thisRestaurant = _db.Restaurants.FirstOrDefault(restaurant => restaurant.RestaurantId == id);
      return View(thisRestaurant);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      Restaurant thisRestaurant = _db.Restaurants.FirstOrDefault(restaurant => restaurant.RestaurantId == id);
      _db.Restaurants.Remove(thisRestaurant);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
  }
}

BestRestaurants/Views/Cuisines/Create.cshtml
@{
  Layout = "_Layout";
}

@model BestRestaurants.Models.Cuisine

<h4>Add a new cuisine</h4>

<p><strong>NOTE:</strong> You need to have at least one restaurant before you can add a cuisine!</p>
<p>Go to @Html.ActionLink("this page", "Create", "Restaurants") to create a restaurant.</p>

@using (Html.BeginForm())
{
  @Html.LabelFor(model => model.Description)
  @Html.TextBoxFor(model => model.Description)

  @Html.LabelFor(model => model.Restaurant)
  @Html.DropDownList("RestaurantId")

  <input type="submit" value="Add new cuisine" class="btn btn-default" />
}
<p>@Html.ActionLink("Show all cuisines", "Index")</p>

BestRestaurants/Views/Cuisines/Delete.cshtml
@{
  Layout = "_Layout";
}

@model BestRestaurants.Models.Cuisine

<h2>Are you sure you want to delete this?</h2>

@Html.DisplayNameFor(model => model.Description): @Html.DisplayFor(model => model.Description)
@using (Html.BeginForm())
{
  <input type="submit" value="Delete" />
}
@Html.ActionLink("Back to List", "Index")

BestRestaurants/Views/Cuisines/Details.cshtml
@{
  Layout = "_Layout";
}

@model BestRestaurants.Models.Cuisine

<h2>Cuisine Details</h2>
<hr />
<h3>@Html.DisplayNameFor(model => model.Description): @Html.DisplayFor(model => model.Description)<h3>
<h3>@Html.DisplayNameFor(model => model.Restaurant): @Html.DisplayFor(model => model.Restaurant.Name)<h3>

<p>@Html.ActionLink("Edit Cuisine", "Edit", new { id = Model.CuisineId })</p>
<p>@Html.ActionLink("Delete Cuisine", "Delete", new { id = Model.CuisineId })</p>
<p>@Html.ActionLink("Back to list", "Index")</p>

BestRestaurants/Views/Cuisines/Edit.cshtml
@{
  Layout = "_Layout";
}

@model BestRestaurants.Models.Cuisine

<h2>Edit</h2>

<h4>Edit this cuisine: @Html.DisplayFor(model => model.Description)</h4>

@using (Html.BeginForm())
{
  @Html.HiddenFor(model => model.CuisineId)

  @Html.LabelFor(model => model.Description)
  @Html.EditorFor(model => model.Description)

  @Html.LabelFor(model => model.Restaurant)
  @Html.DropDownList("RestaurantId")

  <input type="submit" value="Save" />
}

<p>@Html.ActionLink("Back to list", "Index")</p>

BestRestaurants/Views/Cuisines/Index.cshtml
@{
  Layout = "_Layout";
}

@using BestRestaurants.Models;

<h1>Cuisines</h1>

@if (@Model.Count == 0)
{
  <h3>No cuisines have been added yet!</h3>
} 
else
{
  <ul>
    @foreach (Cuisine item in Model)
    {
      <li>@Html.ActionLink($"{item.Description}", "Details", new { id = item.CuisineId }) | @item.Restaurant.Name</li>
    }
  </ul>
}

<p>@Html.ActionLink("Add new cuisine", "Create")</p>
<p>@Html.ActionLink("Home", "Index", "Home")</p>

BestRestaurants/Views/Home/Index.cshtml
@{
  Layout = "_Layout";
}

<div class="jumbotron text-center">
  <h1 class="display-4">Welcome to the Best Restaurants</h1>
  <p class="lead">The best restaurants that serve amazing cuisines from all over the world offer a culinary journey that transcends geographical boundaries and tantalizes taste buds with an array of flavors and textures.</p>
  <hr class="my-4">
  <img src="https://images.pexels.com/photos/1108099/pexels-photo-1108099.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2" alt="dogs" width="90%" >
</div>
<p>@Html.ActionLink("See all cuisines", "Index", "Cuisines")</p> <p>@Html.ActionLink("See all restaurants", "Index", "Restaurants")</p>

BestRestaurants/Views/Restaurants/Create.cshtml
@{
  Layout = "_Layout";
}

@model BestRestaurants.Models.Restaurant

<h4>Add a new restaurant</h4>
@using (Html.BeginForm())
{
  @Html.LabelFor(model => model.Name)
  @Html.TextBoxFor(model => model.Name)
  <input type="submit" value="Add new restaurant" />
}
<p>@Html.ActionLink("Show all restaurants", "Index")</p>

BestRestaurants/Views/Restaurants/Delete.cshtml
@{
  Layout = "_Layout";
}

@model BestRestaurants.Models.Restaurant

<h2>Are you sure you want to delete this?</h2>

@Html.DisplayNameFor(model => model.Name): @Html.DisplayFor(model => model.Name)
@using (Html.BeginForm())
{
  <input type="submit" value="Delete" />
}
@Html.ActionLink("Back to List", "Index")

BestRestaurants/Views/Restaurants/Details.cshtml
@{
  Layout = "_Layout";
}

@model BestRestaurants.Models.Restaurant
@using BestRestaurants.Models

<h2>Restaurant Details</h2>
<hr />
<h3>@Html.DisplayNameFor(model => model.Name): @Html.DisplayFor(model => model.Name)<h3>

@if (@Model.Cuisines.Count == 0)
{
  <h3>No cuisines have been added to this restaurant yet!</h3>
} 
else
{
  <h3>Cuisines:</h3>
  <ul>
    @foreach (Cuisine cuisine in Model.Cuisines)
    {
      <li>@Html.ActionLink($"{cuisine.Description}", "Details", "Cuisines", new { id = cuisine.CuisineId })</li>
    }
  </ul>
}

<p>@Html.ActionLink("Edit Restaurant", "Edit", new { id = Model.RestaurantId })</p>
<p>@Html.ActionLink("Delete Restaurant", "Delete", new { id = Model.RestaurantId })</p>
<p>@Html.ActionLink("Back to list", "Index")</p>

BestRestaurants/Views/Restaurants/Edit.cshtml
@{
  Layout = "_Layout";
}

@model BestRestaurants.Models.Restaurant

<h2>Edit</h2>

<h4>Edit this category: @Html.DisplayFor(model => model.Name)</h4>

@using (Html.BeginForm())
{
  @Html.HiddenFor(model => model.RestaurantId)

  @Html.LabelFor(model => model.Name)
  @Html.EditorFor(model => model.Name)

  <input type="submit" value="Save" />
}
<p>@Html.ActionLink("Back to cuisines", "Index")</p>

BestRestaurants/Views/Restaurants/Index.cshtml
@{
  Layout = "_Layout";
}

@using BestRestaurants.Models;

<h1>Restaurants</h1>

@if (@Model.Count == 0)
{
  <h3>No restaurants have been added yet!</h3>
} 

<ul>
  @foreach(Restaurant restaurant in Model)
  {
    <li>@Html.ActionLink($"{restaurant.Name}", "Details", new { id = restaurant.RestaurantId })</li>
  }
</ul>

<p>@Html.ActionLink("Add new restaurant", "Create")</p>
<p>@Html.ActionLink("Add new cuisine", "Create", "Cuisines")</p>
<p>@Html.ActionLink("Home", "Index", "Home")</p>

BestRestaurants/Views/Shared/Footer.cshtml
<div id="footer">Bottom div content</div>

BestRestaurants/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>My To-Do List!</title>
    <link 
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" 
      rel="stylesheet" 
      integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" 
      crossorigin="anonymous">
    <link rel="stylesheet" href="~/css/styles.css">
  </head>
  <body>
    @RenderBody()
    @await Html.PartialAsync("Footer")
  </body>
</html>